name: Create issues from todos

on:
  push:
    branches:
     - main

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
        - uses: actions/checkout@v1
=======
        - uses: actions/checkout@v3
>>>>>>> 3a0af68 (Update to Checkout v3)
        - name: todo-actions
          uses: dtinth/todo-actions@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
